// Item url dictionary
const searchUrls = {
  // Plate URLs
  'plate hi-temp': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue Bumper Plates by Hi-Temp',
    link: 'https://www.roguefitness.com/rogue-hi-temp-bumper-plates',
    last_avail: null,
    category: 'plate',
  },
  'plate hg2': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue HG 2.0 Bumper Plates',
    link: 'https://www.roguefitness.com/rogue-hg-2-0-bumper-plates',
    last_avail: null,
    category: 'plate',
  },
  'plate hg2 kg': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue HG 2.0 KG Bumper Plates',
    link: 'https://www.roguefitness.com/kg-rogue-bumpers',
    last_avail: null,
    category: 'plate',
  },
  'plate comp lb': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue LB Competition Plates',
    link: 'https://www.roguefitness.com/rogue-competition-plates',
    last_avail: null,
    category: 'plate',
  },
  'plate comp white lb': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue LB Training 2.0 Plates (White Print)',
    link:
      'https://www.roguefitness.com/rogue-lb-training-2-0-plates-white-print',
    last_avail: null,
    category: 'plate',
  },
  'plate comp kg': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue KG Competition Plates (IWF)',
    link: 'https://www.roguefitness.com/rogue-kg-competition-plates-iwf',
    last_avail: null,
    category: 'plate',
  },
  'plate comp lb2': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue Color LB Training 2.0 Plates',
    link: 'https://www.roguefitness.com/rogue-color-lb-training-2-0-plates',
    last_avail: null,
    category: 'plate',
  },
  'plate black lb': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue Black Training LB Plates',
    link:
      'https://www.roguefitness.com/rogue-black-training-lb-color-stripe-plates',
    last_avail: null,
    category: 'plate',
  },
  'plate black lb2': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue LB Training 2.0 Plates',
    link: 'https://www.roguefitness.com/rogue-lb-training-2-0-plates',
    last_avail: null,
    category: 'plate',
  },
  'plate black kg': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue Black Training KG Plates',
    link: 'https://www.roguefitness.com/rogue-black-training-kg-striped-plates',
    last_avail: null,
    category: 'plate',
  },
  'plate echo v2': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue Echo Bumper Plates V2',
    link:
      'https://www.roguefitness.com/rogue-echo-bumper-plates-with-white-text',
    last_avail: null,
    category: 'plate',
  },
  'plate echo v1': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue Echo Bumper Plates V1',
    link:
      'https://www.roguefitness.com/rogue-echo-bumper-plates-with-white-text-v1',
    last_avail: null,
    category: 'plate',
  },
  'plate echo color': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue Color Echo Bumper Plates',
    link: 'https://www.roguefitness.com/rogue-color-echo-bumper-plate',
    last_avail: null,
    category: 'plate',
  },
  'plate machined': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue Machined Olympic Plates',
    link: 'https://www.roguefitness.com/rogue-machined-olympic-plates',
    last_avail: null,
    category: 'plate',
  },
  'plate fleck': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue Fleck Plate',
    link: 'https://www.roguefitness.com/rogue-fleck-plates',
    last_avail: null,
    category: 'plate',
  },
  'plate olympic': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue Olympic Plates',
    link: 'https://www.roguefitness.com/rogue-olympic-plates',
    last_avail: null,
    category: 'plate',
  },
  'plate cal': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue Calibrated LB Steel Plates',
    link: 'https://www.roguefitness.com/rogue-calibrated-lb-steel-plates',
    last_avail: null,
    category: 'plate',
  },
  'plate change': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue LB Change Plates',
    link: 'https://www.roguefitness.com/rogue-lb-change-plates',
    last_avail: null,
    category: 'plate',
  },
  'plate change kg': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue KG Change Plates (IWF)',
    link: 'https://www.roguefitness.com/rogue-kg-change-plates',
    last_avail: null,
    category: 'plate',
  },
  'plate mil spec': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue US-MIL Spec Bumper',
    link: 'https://www.roguefitness.com/rogue-us-mil-sprc-bumper-plates',
    last_avail: null,
    category: 'plate',
  },
  'plate mil spec echo': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue MIL Spec Echo Bumper',
    link: 'https://www.roguefitness.com/rogue-mil-echo-bumper-plates-black',
    last_avail: null,
    category: 'plate',
  },
  'plate 6-shooter': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue 6-Shooter Olympic Grip Plates',
    link: 'https://www.roguefitness.com/rogue-6-shooter-olympic-plates',
    last_avail: null,
    category: 'plate',
  },
  'plate cal kg': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue Calibrated KG Steel Plates',
    link: 'https://www.roguefitness.com/rogue-calibrated-kg-steel-plates',
    last_avail: null,
    category: 'plate',
  },
  'plate urethane': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue Urethane Plates',
    link: 'https://www.roguefitness.com/rogue-urethane-plates',
    last_avail: null,
    category: 'plate',
  },
  'plate tree': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue Vertical Plate Tree 2.0',
    link: 'https://www.roguefitness.com/rogue-vertical-plate-tree-2-0',
    last_avail: null,
    category: 'storage',
  },
  // Barbell URLs
  // Ohio Bar
  'barbell op oxide': {
    type: 'single',
    senderIDs: {},
    product_name: 'The Ohio Bar - Black Oxide',
    link: 'https://www.roguefitness.com/rogue-ohio-bar-black-oxide',
    last_avail: null,
    category: 'barbell',
  },
  'barbell op zinc': {
    type: 'single',
    senderIDs: {},
    product_name: 'The Ohio Bar - Black Zinc',
    link: 'https://www.roguefitness.com/the-ohio-bar-black-zinc',
    last_avail: null,
    category: 'barbell',
  },
  'barbell op ecoat': {
    type: 'single',
    senderIDs: {},
    product_name: 'The Ohio Bar - E-Coat',
    link: 'https://www.roguefitness.com/the-ohio-bar-2-0-e-coat',
    last_avail: null,
    category: 'barbell',
  },
  'barbell op ss': {
    type: 'single',
    senderIDs: {},
    product_name: 'The Ohio Bar - Stainless Steel',
    link: 'https://www.roguefitness.com/stainless-steel-ohio-bar',
    last_avail: null,
    category: 'barbell',
  },
  'barbell op cerakote': {
    type: 'cerakote',
    senderIDs: {},
    product_name: 'The Ohio Bar - Cerakote',
    link: 'https://www.roguefitness.com/the-ohio-bar-cerakote',
    last_avail: null,
    category: 'barbell',
  },
  'barbell op fraser': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue Athlete Cerakote Ohio Bar - Fraser Edition',
    link:
      'https://www.roguefitness.com/rogue-athlete-ohio-bar-fraser-cerakote-edition',
    last_avail: null,
    category: 'barbell',
  },
  // Ohio Power Bar
  'barbell opb steel': {
    type: 'single',
    senderIDs: {},
    product_name: 'Rogue 45LB Ohio Power Bar - Bare Steel',
    link: 'https://www.roguefitness.com/rogue-45lb-ohio-power-bar-bare-steel',
    last_avail: null,
    category: 'barbell',
  },
  'barbell opb ecoat': {
    type: 'single',
    senderIDs: {},
    product_name: 'Rogue 45LB Ohio Power Bar - E-Coat',
    link: 'https://www.roguefitness.com/rogue-ohio-power-bar-e-coat',
    last_avail: null,
    category: 'barbell',
  },
  'barbell opb zinc': {
    type: 'single',
    senderIDs: {},
    product_name: 'Rogue 45LB Ohio Power Bar - Black Zinc',
    link: 'https://www.roguefitness.com/rogue-45lb-ohio-power-bar-black-zinc',
    last_avail: null,
    category: 'barbell',
  },
  'barbell opb ss': {
    type: 'custom',
    senderIDs: {},
    product_name: 'Rogue 45LB Ohio Power Bar - Stainless Steel',
    link: 'https://www.roguefitness.com/rogue-45lb-ohio-power-bar-stainless',
    last_avail: null,
    category: 'barbell',
  },
  'barbell opb ss kg': {
    type: 'single',
    senderIDs: {},
    product_name: 'Rogue 20KG Ohio Power Bar - Stainless Steel',
    link:
      'https://www.roguefitness.com/rogue-20-kg-ohio-power-bar-stainless-steel',
    last_avail: null,
    category: 'barbell',
  },
  'barbell opb cerakote': {
    type: 'cerakote',
    senderIDs: {},
    product_name: 'Rogue 45LB Ohio Power Bar - Cerakote',
    link: 'https://www.roguefitness.com/rogue-45lb-ohio-powerlift-bar-cerakote',
    last_avail: null,
    category: 'barbell',
  },
  'barbell dl cerakote': {
    type: 'cerakote',
    senderIDs: {},
    product_name: 'Rogue Ohio Deadlift Bar - Cerakote',
    link: 'https://www.roguefitness.com/rogue-ohio-deadlift-cerakote',
    last_avail: null,
    category: 'barbell',
  },
  // Boneyard
  'bone 29': {
    type: 'bone',
    senderIDs: {},
    product_name: 'Boneyard 29mm Bars',
    link: 'https://www.roguefitness.com/rogue-29mm-boneyard-bars',
    last_avail: null,
    category: 'boneyard',
  },
  'bone 28': {
    type: 'bone',
    senderIDs: {},
    product_name: 'Boneyard 28mm Bars',
    link: 'https://www.roguefitness.com/rogue-28mm-boneyard-bars',
    last_avail: null,
    category: 'boneyard',
  },
  'bone 28.5': {
    type: 'bone',
    senderIDs: {},
    product_name: 'Boneyard 28.5mm Bars',
    link: 'https://www.roguefitness.com/rogue-28-5-mm-boneyard-bars',
    last_avail: null,
    category: 'boneyard',
  },
  'bone dead': {
    type: 'bone',
    senderIDs: {},
    product_name: 'Boneyard Deadlift Bars',
    link: 'https://www.roguefitness.com/rogue-boneyard-ohio-deadlift-bar',
    last_avail: null,
    category: 'boneyard',
  },
  'bone curl': {
    type: 'bone',
    senderIDs: {},
    product_name: 'Boneyard Curl Bars',
    link: 'https://www.roguefitness.com/rogue-boneyard-curl-bar',
    last_avail: null,
    category: 'boneyard',
  },
  'bone 25': {
    type: 'bone',
    senderIDs: {},
    product_name: 'Rogue 25MM Boneyard Bars',
    link: 'https://www.roguefitness.com/rogue-25mm-boneyard-bars',
    last_avail: null,
    category: 'boneyard',
  },
  'grab bag barbell': {
    type: 'grab bag',
    senderIDs: {},
    product_name: 'Used Barbells',
    link: 'https://www.roguefitness.com/miscellaneous-barbells-used',
    last_avail: null,
    category: 'boneyard',
  },
  'bone oso pro': {
    type: 'bone',
    senderIDs: {},
    product_name: 'Boneyard OSO Pro Collars',
    link: 'https://www.roguefitness.com/boneyard-oso-pro-collars-closeout',
    last_avail: null,
    category: 'boneyard',
  },
  // Ironmaster
  'ironmaster adj 75': {
    type: 'ironmaster',
    senderIDs: {},
    product_name: 'Quick-Lock Adjustable Dumbbell System 75 lb Set',
    link:
      'https://www.ironmaster.com/products/quick-lock-adjustable-dumbbells-75/',
    last_avail: null,
    category: 'ironmaster',
  },
  'ironmaster adj 45': {
    type: 'ironmaster',
    senderIDs: {},
    product_name: 'Quick-Lock Adjustable Dumbbell System 45 lb Set',
    link:
      'https://www.ironmaster.com/products/quick-lock-dumbbell-system-45-lb-set/',
    last_avail: null,
    category: 'ironmaster',
  },
  'ironmaster addon 120': {
    type: 'ironmaster',
    senderIDs: {},
    product_name: 'Quick-Lock Dumbbell – 120 lb Add on Kit ',
    link:
      'https://www.ironmaster.com/products/add-on-kit-to-120-lbs-quick-lock/',
    last_avail: null,
    category: 'ironmaster',
  },
  // Bella Bars
  'bella ecoat': {
    type: 'single',
    senderIDs: {},
    product_name: 'The Bella Bar 2.0 - E-Coat',
    link: 'https://www.roguefitness.com/the-bella-bar-2-0-e-coat',
    last_avail: null,
    category: 'barbell',
  },
  'bella zinc': {
    type: 'single',
    senderIDs: {},
    product_name: 'The Bella Bar 2.0 - Black Zinc',
    link: 'https://www.roguefitness.com/rogue-bella-bar-2-0-black-zinc',
    last_avail: null,
    category: 'barbell',
  },
  'bella ss': {
    type: 'single',
    senderIDs: {},
    product_name: 'The Bella Bar 2.0 - Stainless Steel',
    link: 'https://www.roguefitness.com/the-bella-bar-2-0-stainless',
    last_avail: null,
    category: 'barbell',
  },
  'bella cerakote': {
    type: 'cerakote',
    senderIDs: {},
    product_name: 'The Bella Bar 2.0 - Cerakote',
    link: 'https://www.roguefitness.com/the-bella-rogue-womens-bar-cerakote',
    last_avail: null,
    category: 'barbell',
  },
  'barbell operator': {
    type: 'cerakote',
    senderIDs: {},
    product_name: 'Rogue Operator Bar 3.0',
    link: 'https://www.roguefitness.com/rogue-operator-bar-cerakote',
    last_avail: null,
    category: 'barbell',
  },
  'barbell chan': {
    type: 'cerakote',
    senderIDs: {},
    product_name: 'Rogue Chan Bar - Cerakote',
    link: 'https://www.roguefitness.com/chan-bar-cerakote',
    last_avail: null,
    category: 'barbell',
  },
  'barbell training zinc': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue 28MM Training Bar - Black Zinc',
    link: 'https://www.roguefitness.com/rogue-28mm-training-bar',
    last_avail: null,
    category: 'barbell',
  },
  'barbell training cerakote': {
    type: 'cerakote',
    senderIDs: {},
    product_name: 'Rogue 28MM Training Bar - Cerakote',
    link: 'https://www.roguefitness.com/rogue-28mm-training-bar-cerakote',
    last_avail: null,
    category: 'barbell',
  },
  'barbell b&r': {
    type: 'single',
    senderIDs: {},
    product_name: 'Rogue B&R Bar 2.0',
    link: 'https://www.roguefitness.com/rogue-29mm-burgener-rippetoe-bar-2-0',
    last_avail: null,
    category: 'barbell',
  },
  // Curl Bar
  'curl cerakote': {
    type: 'single',
    senderIDs: {},
    product_name: 'Rogue Curl Bar - Cerakote',
    link: 'https://www.roguefitness.com/rogue-curl-bar-cerakote',
    last_avail: null,
    category: 'spec_bar',
  },
  curl: {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue Curl Bar',
    link: 'https://www.roguefitness.com/rogue-curl-bar',
    last_avail: null,
    category: 'spec_bar',
  },
  'curl rackable': {
    type: 'single',
    senderIDs: {},
    product_name: 'Rogue Rackable Curl Bar',
    link: 'https://www.roguefitness.com/rogue-rackable-curl-bar',
    last_avail: null,
    category: 'spec_bar',
  },
  // Other bars
  'barbell rogue 2.0': {
    type: 'multi',
    senderIDs: {},
    product_name: 'The Rogue Bar 2.0',
    link: 'https://www.roguefitness.com/the-rogue-bar-2-0',
    last_avail: null,
    category: 'barbell',
  },
  'barbell echo 2.0': {
    type: 'single',
    senderIDs: {},
    product_name: 'Rogue Echo Bar 2.0',
    link: 'https://www.roguefitness.com/rogue-echo-bar',
    last_avail: null,
    category: 'barbell',
  },
  'barbell freedom': {
    type: 'single',
    senderIDs: {},
    product_name: 'Rogue Freedom Bar - 28.5MM',
    link: 'https://www.roguefitness.com/cerakote-28-5-mm-freedom-bar',
    last_avail: null,
    category: 'barbell',
  },
  'db 15': {
    type: 'db15',
    senderIDs: {},
    product_name: 'Rogue DB-15 Loadable Dumbbell',
    link: 'https://www.roguefitness.com/rogue-loadable-dumbbells',
    last_avail: null,
    category: 'cond',
  },
  'db 10': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue DB-10 Loadable Dumbbell',
    link: 'https://www.roguefitness.com/rogue-loadable-dumbbells',
    last_avail: null,
    category: 'cond',
  },
  // Echo bike
  'bike echo': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue Echo Bike',
    link: 'https://www.roguefitness.com/rogue-echo-bike',
    last_avail: null,
    category: 'cardio',
  },
  // Bench
  'bench monster 2.0': {
    type: 'monster bench',
    senderIDs: {},
    product_name: 'Monster Utility Bench 2.0',
    link: 'https://www.roguefitness.com/monster-utility-bench-2-0-mg-black',
    last_avail: null,
    category: 'bench',
  },
  'bench flat 2.0': {
    type: 'single',
    senderIDs: {},
    product_name: 'Rogue Flat Utility Bench 2.0',
    link: 'https://www.roguefitness.com/rogue-flat-utility-bench',
    last_avail: null,
    category: 'bench',
  },
  'bench adj 2.0': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue Adjustable Bench 2.0',
    link: 'https://www.roguefitness.com/rogue-adjustable-bench-2-0',
    last_avail: null,
    category: 'bench',
  },
  'bench ab2': {
    type: 'multi',
    senderIDs: {},
    product_name: 'AB-2 Adjustable Bench',
    link: 'https://www.roguefitness.com/ab-2-adjustable-bench',
    last_avail: null,
    category: 'bench',
  },
  'bench ab3': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue AB-3 Adjustable Bench',
    link: 'https://www.roguefitness.com/rogue-ab-3-adjustable-bench',
    last_avail: null,
    category: 'bench',
  },
  'bench thompson': {
    type: 'single',
    senderIDs: {},
    product_name: 'Thompson Fat Pad™',
    link: 'https://www.roguefitness.com/thompson-fatpad',
    last_avail: null,
    category: 'bench',
  },
  'bench fatpad': {
    type: 'single',
    senderIDs: {},
    product_name: 'Rogue Competition Fat Pad',
    link: 'https://www.roguefitness.com/rogue-competition-fat-pad',
    last_avail: null,
    category: 'bench',
  },
  'bench foldup': {
    type: 'single',
    senderIDs: {},
    product_name: 'Rogue Fold Up Utility Bench',
    link: 'https://www.roguefitness.com/rogue-fold-up-utility-bench',
    last_avail: null,
    category: 'bench',
  },
  'bench westside 2.0': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue Westside Bench 2.0',
    link: 'https://www.roguefitness.com/rogue-westside-bench-2-0',
    last_avail: null,
    category: 'bench',
  },
  'bench monster westside': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue Monster Westside Bench',
    link: 'https://www.roguefitness.com/rogue-monster-westside-bench',
    last_avail: null,
    category: 'bench',
  },
  // Squat Stands
  'squat sml-2': {
    type: 'multi',
    senderIDs: {},
    product_name: 'SML-2 Rogue 90" Monster Lite Squat Stand',
    link:
      'https://www.roguefitness.com/sml-2-rogue-90-monster-lite-squat-stand',
    last_avail: null,
    category: 'squat stand',
  },
  'squat sml-3': {
    type: 'multi',
    senderIDs: {},
    product_name: 'SML-3 Rogue 108" Monster Lite Squat Stand',
    link:
      'https://www.roguefitness.com/sml-3-rogue-108-monster-lite-squat-stand',
    last_avail: null,
    category: 'squat stand',
  },
  'squat s-1': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue S-1 Squat Stand 2.0',
    link: 'https://www.roguefitness.com/rogue-s-1-squat-stand-2-0',
    last_avail: null,
    category: 'squat stand',
  },
  'squat s-2': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue S-2 Squat Stand 2.0',
    link: 'https://www.roguefitness.com/rogue-s2-squat-stand-2-0',
    last_avail: null,
    category: 'squat stand',
  },
  'squat s-4': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue S-4 Squat Stand 2.0',
    link: 'https://www.roguefitness.com/rogue-s-4-squat-stand-2',
    last_avail: null,
    category: 'squat stand',
  },
  'squat echo': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue Echo Squat Stand 2.0',
    link: 'https://www.roguefitness.com/rogue-echo-squat-stand-2-0',
    last_avail: null,
    category: 'squat stand',
  },
  // Racks
  'rack rml-390f': {
    type: 'multi',
    senderIDs: {},
    product_name: 'RML-390F Flat Foot Monster Lite Rack',
    link: 'https://www.roguefitness.com/rml-390f-flat-foot-monster-lite-rack',
    last_avail: null,
    category: 'rack',
  },
  'rack rml-490': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue RML-490 Power Rack',
    link: 'https://www.roguefitness.com/rogue-rml-490-power-rack',
    last_avail: null,
    category: 'rack',
  },
  'rack rml-490c': {
    type: 'rmlc',
    senderIDs: {},
    product_name: 'Rogue RML-490C Power Rack 3.0',
    link: 'https://www.roguefitness.com/rogue-rml-490-power-rack-color-3-0',
    last_avail: null,
    category: 'rack',
  },
  'rack rml-690': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue RML-690 Power Rack',
    link: 'https://www.roguefitness.com/rml-690-power-rack',
    last_avail: null,
    category: 'rack',
  },
  'rack r-3': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue R-3 Power Rack',
    link: 'https://www.roguefitness.com/rogue-r-3-power-rack',
    last_avail: null,
    category: 'rack',
  },
  'rack rm-3 fortis': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue RM-3 Fortis Rack',
    link: 'https://www.roguefitness.com/rogue-rm-3-fortis-rack',
    last_avail: null,
    category: 'rack',
  },
  'rack rm-4 fortis': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue RM-4 Fortis Rack',
    link: 'https://www.roguefitness.com/rogue-rm-4-fortis-rack',
    last_avail: null,
    category: 'rack',
  },
  'combo rack': {
    type: 'single',
    senderIDs: {},
    product_name: 'Rogue Combo Rack',
    link: 'https://www.roguefitness.com/rogue-combo-rack',
    last_avail: null,
    category: 'rack',
  },
  'ml spotter': {
    type: 'single',
    senderIDs: {},
    product_name: 'SAML-24 Monster Lite Safety Spotter Arms (Pair)',
    link: 'https://www.roguefitness.com/saml-24-monster-lite-spotter-arms-pair',
    last_avail: null,
    category: 'ml',
  },
  'm spotter': {
    type: 'single',
    senderIDs: {},
    product_name: 'Monster Safety Spotter Arms 2.0',
    link: 'https://www.roguefitness.com/monster-safety-spotter-arms-2-0',
    last_avail: null,
    category: 'm',
  },
  'm top beam': {
    type: 'custom2',
    senderIDs: {},
    product_name: 'Monster 43 Top Beam',
    link: 'https://www.roguefitness.com/monster-43-top-beam',
    last_avail: null,

    category: 'm',
  },
  'm slinger': {
    type: 'custom2',
    senderIDs: {},
    product_name: 'Rogue Monster Slinger',
    link: 'https://www.roguefitness.com/rogue-monster-slinger',
    last_avail: null,

    category: 'm',
  },
  'm attach post': {
    type: 'single',
    senderIDs: {},
    product_name: 'Rogue Monster Attachment Post',
    link: 'https://www.roguefitness.com/rogue-monster-attachment-post',
    last_avail: null,
    category: 'm',
  },
  'infinity spotter': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue Infinity Safety Spotter Arms',
    link: 'https://www.roguefitness.com/set-of-safety-spotter-arms',
    last_avail: null,
    category: 'inf',
  },
  'ml straps': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Monster Lite Strap Safety System 2.0',
    link: 'https://www.roguefitness.com/monster-lite-strap-safety-system-2-0',
    last_avail: null,
    category: 'ml',
  },
  'infinity straps': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Infinity Strap Safety System 2.0',
    link: 'https://www.roguefitness.com/infinity-strap-safety-system-2-0',
    last_avail: null,
    category: 'inf',
  },
  'infinity j-cups': {
    type: 'single',
    senderIDs: {},
    product_name: 'Rogue Infinity J-Cup Set',
    link: 'https://www.roguefitness.com/extra-infinity-j-cup-set',
    last_avail: null,
    category: 'inf',
  },
  'ml j-cups': {
    type: 'single',
    senderIDs: {},
    product_name: 'Monster Lite J-Cups',
    link: 'https://www.roguefitness.com/j-3358-monster-lite-j-cups',
    last_avail: null,
    category: 'ml',
  },
  'ml sandwich j-cups': {
    type: 'single',
    senderIDs: {},
    product_name: 'Monster Lite Sandwich J-Cup Pair',
    link: 'https://www.roguefitness.com/monster-lite-sandwich-j-cup-pair',
    last_avail: null,
    category: 'ml',
  },
  'ml slinger': {
    type: 'custom2',
    senderIDs: {},
    product_name: 'Rogue Monster Lite Slinger',
    link: 'https://www.roguefitness.com/rogue-monster-lite-slinger',
    last_avail: null,

    category: 'ml',
  },
  landmine: {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue Landmines',
    link: 'https://www.roguefitness.com/landmines',
    last_avail: null,
    category: 'ml',
  },
  'm landmine': {
    type: 'single',
    senderIDs: {},
    product_name: 'Rogue Monster Landmine 2.0',
    link: 'https://www.roguefitness.com/rogue-monster-landmine-2-0',
    last_avail: null,
    category: 'm',
  },
  'parallel landmine handle': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue Parallel Landmine Handle',
    link: 'https://www.roguefitness.com/rogue-parallel-landmine-handle',
    last_avail: null,
    category: 'acc',
  },
  // Yoke
  'yoke y1': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Y-1 Rogue Yoke',
    link: 'https://www.roguefitness.com/rogue-yoke',
    last_avail: null,
    category: 'other',
  },
  'yoke y2': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Y-2 Rogue Yoke',
    link: 'https://www.roguefitness.com/y2-yoke',
    last_avail: null,
    category: 'other',
  },
  // Row
  'rower pm5': {
    type: 'single',
    senderIDs: {},
    product_name: 'Black Concept 2 Model D Rower - PM5',
    link: 'https://www.roguefitness.com/black-concept-2-model-d-rower-pm5',
    last_avail: null,
    category: 'cardio',
  },
  // GHD
  'abram ghd': {
    type: 'single',
    senderIDs: {},
    product_name: 'Rogue Abram GHD 2.0',
    link: 'https://www.roguefitness.com/rogue-abram-glute-ham-developer-2-0',
    last_avail: null,
    category: 'other',
  },
  'm ghd': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue Monster Swing Arm GHD',
    link: 'https://www.roguefitness.com/rogue-monster-swing-arm-ghd',
    last_avail: null,
    category: 'other',
  },
  'echo ghd': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue 3x3 Echo GHD',
    link: 'https://www.roguefitness.com/rogue-echo-ghd',
    last_avail: null,
    category: 'other',
  },
  'mini dl jack': {
    type: 'single',
    senderIDs: {},
    product_name: 'Mini Deadlift Bar Jack',
    link: 'https://www.roguefitness.com/mini-deadlift-bar-jack',
    last_avail: null,
    category: 'acc',
  },
  'dl jack': {
    type: 'single',
    senderIDs: {},
    product_name: 'Rogue Deadlift Bar Jack',
    link: 'https://www.roguefitness.com/bar-jack',
    last_avail: null,
    category: 'acc',
  },
  // Free weights
  kettlebells: {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue Kettlebells',
    link: 'https://www.roguefitness.com/rogue-kettlebells',
    last_avail: null,
    category: 'cond',
  },
  'kettlebells comp': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue Competition Kettlebells',
    link: 'https://www.roguefitness.com/rogue-competition-kettlebells',
    last_avail: null,
    category: 'cond',
  },
  'kettlebells ecoat': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue Kettlebell - E Coat',
    link: 'https://www.roguefitness.com/rogue-kettlebell-e-coat',
    last_avail: null,
    category: 'cond',
  },
  dumbbells: {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue Dumbbells',
    link: 'https://www.roguefitness.com/rogue-dumbbells',
    last_avail: null,
    category: 'cond',
  },
  'dumbbell sets': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue Dumbbell Sets',
    link: 'https://www.roguefitness.com/rogue-rubber-hex-dumbbell-sets',
    last_avail: null,
    category: 'cond',
  },
  'medicine balls': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue Medicine Balls',
    link: 'https://www.roguefitness.com/rogue-medicine-balls',
    last_avail: null,
    category: 'cond',
  },
  fatbells: {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue Thompson Fatbells',
    link: 'https://www.roguefitness.com/rogue-thompson-fatbells',
    last_avail: null,
    category: 'cond',
  },
  'm monolift': {
    type: 'single',
    senderIDs: {},
    product_name: 'Rogue Adjustable Monolift - Monster',
    link: 'https://www.roguefitness.com/rogue-adjustable-monolift-monster',
    last_avail: null,
    category: 'm',
  },
  'ml monolift': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue Adjustable Monolift - Monster Lite',
    link: 'https://www.roguefitness.com/rogue-adjustable-monolift-monster-lite',
    last_avail: null,
    category: 'ml',
  },
  'm mini feet': {
    type: 'single',
    senderIDs: {},
    product_name: 'Rogue Monster Mini Feet',
    link: 'https://www.roguefitness.com/rogue-monster-mini-feet',
    last_avail: null,
    category: 'm',
  },
  'm plate storage long': {
    type: 'single',
    senderIDs: {},
    product_name: 'SP33100 Plate Storage Pair - Long for 3x3 Monster',
    link:
      'https://www.roguefitness.com/sp33100-plate-storage-long-for-3x3-monster',
    last_avail: null,
    category: 'm',
  },
  'm single post shelf': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Monster Single Post Storage Shelf',
    link: 'https://www.roguefitness.com/monster-single-post-storage-shelf',
    last_avail: null,
    category: 'm',
  },
  'm storage pin': {
    type: 'custom2',
    senderIDs: {},
    product_name: 'Rogue Monster Plate Storage Pin',
    link:
      'https://www.roguefitness.com/rogue-monster-keyhole-keyless-plate-storage-pin',
    last_avail: null,
    category: 'm',
  },
  'm j-cup pairs': {
    type: 'custom2',
    senderIDs: {},
    product_name: 'Monster J-Cup Pairs',
    link: 'https://www.roguefitness.com/monster-j-cup-pairs',
    last_avail: null,
    category: 'm',
  },
  'barbell iwf': {
    type: 'single',
    senderIDs: {},
    product_name:
      'Rogue 28MM IWF Olympic Weightlifting Bar w/ Center Knurl - Bright Zinc',
    link:
      'https://www.roguefitness.com/rogue-iwf-olympic-wl-bar-w-center-knurl-bright-zinc',
    last_avail: null,
    category: 'barbell',
  },
  'rack r-3bt': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue Bolt-Together R-3',
    link: 'https://www.roguefitness.com/rogue-bolt-together-r-3',
    last_avail: null,
    category: 'rack',
  },
  'm matador': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue Monster Matador',
    link: 'https://www.roguefitness.com/rogue-monster-matador',
    last_avail: null,
    category: 'm',
  },
  'ml matador': {
    type: 'single',
    senderIDs: {},
    product_name: 'Rogue Monster Lite Matador',
    link: 'https://www.roguefitness.com/rogue-monster-lite-matador',
    last_avail: null,
    category: 'ml',
  },
  'ml plate storage long': {
    type: 'single',
    senderIDs: {},
    product_name: 'SP3358 Plate Storage Pair - Long for Monster Lite',
    link:
      'https://www.roguefitness.com/sp3358-plate-storage-long-for-monster-lite',
    last_avail: null,

    category: 'ml',
  },
  'ml pin pipe': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Infinity/ML Pin and Pipe Safeties',
    link: 'https://www.roguefitness.com/infinity-ml-pin-pipe-safeties',
    last_avail: null,

    category: 'ml',
  },
  'ml band pegs': {
    type: 'single',
    senderIDs: {},
    product_name: 'Rogue Monster Lite/Infinity Band Pegs - 4 Pack',
    link: 'https://www.roguefitness.com/extra-set-of-band-pegs',
    last_avail: null,
    category: 'ml',
  },
  'infinity matador': {
    type: 'single',
    senderIDs: {},
    product_name: 'Rogue Infinity Matador',
    link: 'https://www.roguefitness.com/rogue-infinity-matador',
    last_avail: null,
    category: 'inf',
  },
  'assault airbike': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Assault AirBike',
    link: 'https://www.roguefitness.com/assault-airbike-and-accessories',
    last_avail: null,
    category: 'cardio',
  },
  'trolley lever arm kit': {
    type: 'trolley',
    senderIDs: {},
    product_name: 'Rogue LT-1 Trolley and Lever Arm Kit',
    link:
      'https://www.roguefitness.com/rogue-lt-1-50-cal-trolley-lever-arms-kit',
    last_avail: null,
    category: 'acc',
  },
  'usa alum collars': {
    type: 'custom2',
    senderIDs: {},
    product_name: 'Rogue USA Aluminum Collars',
    link: 'https://www.roguefitness.com/rogue-usa-aluminum-collars',
    last_avail: null,
    category: 'acc',
  },
  'ah-1 articulating': {
    type: 'single',
    senderIDs: {},
    product_name: 'H-1 Articulating Handle Kit',
    link: 'https://www.roguefitness.com/monster-ah-1-articulating-handle-kit',
    last_avail: null,
    category: 'm',
  },
  bikeerg: {
    type: 'single',
    senderIDs: {},
    product_name: 'Concept 2 BikeErg',
    link: 'https://www.roguefitness.com/concept2-bike-erg',
    last_avail: null,
    category: 'cardio',
  },
  'landmine post': {
    type: 'single',
    senderIDs: {},
    product_name: 'Post Landmine',
    link: 'https://www.roguefitness.com/post-landmine',
    last_avail: null,
    category: 'acc',
  },
  'plate wagon': {
    type: 'single',
    senderIDs: {},
    product_name: 'Rogue 26 ER Wagon Wheel Pair',
    link: 'https://www.roguefitness.com/rogue-26-er-wagon-wheel-pair',
    last_avail: null,

    category: 'plate',
  },
  'camber bar': {
    type: 'single',
    senderIDs: {},
    product_name: 'CB-1 Rogue Camber Bar',
    link: 'https://www.roguefitness.com/cb-1-rogue-camber-bar',
    last_avail: null,
    category: 'spec_bar',
  },
  'dl platform': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue Deadlift Platform',
    link: 'https://www.roguefitness.com/rogue-deadlift-platform',
    last_avail: null,
    category: 'other',
  },
  'dumbbell bumpers': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue Dumbbell Bumpers',
    link: 'https://www.roguefitness.com/rogue-dumbbell-bumpers',
    last_avail: null,
    category: 'cond',
  },
  'ab wheel': {
    type: 'single',
    senderIDs: {},
    product_name: 'Ab Wheel',
    link: 'https://www.roguefitness.com/ab-wheel',
    last_avail: null,
    category: 'acc',
  },
  'ss lat bar': {
    type: 'single',
    senderIDs: {},
    product_name: 'Rogue Stainless Lat Bar',
    link: 'https://www.roguefitness.com/rogue-stainless-steel-lat-bar',
    last_avail: null,
    category: 'acc',
  },
  'ml adj pullup': {
    type: 'single',
    senderIDs: {},
    product_name: 'Rogue Monster Lite Adjustable Pull-up Bar',
    link:
      'https://www.roguefitness.com/rogue-monster-lite-adjustable-pull-up-bar',
    last_avail: null,
    category: 'ml',
  },
  'm rhino belt squat': {
    type: 'single',
    senderIDs: {},
    product_name: 'Rogue Monster Rhino Belt Squat - Stand Alone',
    link:
      'https://www.roguefitness.com/monster-rhino-belt-squat-stand-alone-mg-black',
    last_avail: null,
    category: 'm',
  },
  'm grip triangle': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue Monster Grip Triangle',
    link: 'https://www.roguefitness.com/rogue-monster-grip-triangle',
    last_avail: null,
    category: 'm',
  },
  'trap tb1': {
    type: 'single',
    senderIDs: {},
    product_name: 'Rogue TB-1 Trap Bar 2.0',
    link: 'https://www.roguefitness.com/rogue-tb-1-trap-bar-2-0',
    last_avail: null,
    category: 'spec_bar',
  },
  'trap tb2': {
    type: 'single',
    senderIDs: {},
    product_name: 'Rogue TB-2 Trap Bar',
    link: 'https://www.roguefitness.com/rogue-tb-2-trap-bar',
    last_avail: null,
    category: 'spec_bar',
  },
  'grip triangle': {
    type: 'single',
    senderIDs: {},
    product_name: 'Rogue Grip Triangle (Standard Grip)',
    link: 'https://www.roguefitness.com/rogue-grip-triangle-standard-grip',
    last_avail: null,
    category: 'acc',
  },
  'tricep pushdown': {
    type: 'single',
    senderIDs: {},
    product_name: 'Rogue Tricep Push Down Attachment',
    link: 'https://www.roguefitness.com/rogue-tricep-pushdown-attachment',
    last_avail: null,
    category: 'acc',
  },
  't-bar row': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue T Bar Row',
    link: 'https://www.roguefitness.com/rogue-t-bar-row',
    last_avail: null,
    category: 'acc',
  },
  'xm-43m crossmember': {
    type: 'single',
    senderIDs: {},
    product_name: 'XM-43M Monster Multi Grip Crossmember',
    link: 'https://www.roguefitness.com/xm-43m-monster-multi-grip-crossmember',
    last_avail: null,
    category: 'm',
  },
  'ml crossmember': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Monster Lite Crossmembers',
    link: 'https://www.roguefitness.com/monster-lite-crossmembers',
    last_avail: null,
    category: 'ml',
  },
  'echo gym timer': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue Echo Gym Timer',
    link: 'https://www.roguefitness.com/rogue-echo-gym-timer',
    last_avail: null,
    category: 'acc',
  },
  'home timer': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue Home Timer',
    link: 'https://www.roguefitness.com/rogue-home-timer',
    last_avail: null,
    category: 'acc',
  },
  'ml shackle': {
    type: 'single',
    senderIDs: {},
    product_name: 'Rogue Monster Lite Shackle',
    link: 'https://www.roguefitness.com/rogue-monster-lite-shackle',
    last_avail: null,
    category: 'ml',
  },
  'm shackle': {
    type: 'single',
    senderIDs: {},
    product_name: 'Rogue Monster Shackle',
    link: 'https://www.roguefitness.com/rogue-monster-shackle',
    last_avail: null,
    category: 'm',
  },
  'mg-2 multi grip': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue MG-2 Multi Grip Bars',
    link: 'https://www.roguefitness.com/rogue-mg-2-multi-grip-bars',
    last_avail: null,
    category: 'spec_bar',
  },
  'mg-3 multi grip': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue MG-3 Multi Grip Bar',
    link: 'https://www.roguefitness.com/rogue-mg-3-multi-grip-bar',
    last_avail: null,
    category: 'spec_bar',
  },
  'barbell 25mm iwf zinc': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue 25MM IWF Olympic Weightlifting Bar - Bright Zinc',
    link: 'https://www.roguefitness.com/rogue-25mm-wmns-oly-bar-dome-cap',
    last_avail: null,
    category: 'barbell',
  },
  'barbell 25mm iwf cerakote': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue 25MM IWF Olympic Weightlifting Bar - Cerakote',
    link: 'https://www.roguefitness.com/rogue-25mm-iwf-oly-bar-cerakote',
    last_avail: null,

    category: 'barbell',
  },
  'barbell westside': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue Westside Power Bar 2.0',
    link: 'https://www.roguefitness.com/rogue-westside-power-bar-2-0',
    last_avail: null,

    category: 'barbell',
  },
  'barbell toomey': {
    type: 'multi',
    senderIDs: {},
    product_name: 'The Bella Bar - Cerakote - Tia-Clair Toomey Edition',
    link:
      'https://www.roguefitness.com/rogue-athlete-bella-bar-cerakote-toomey',
    last_avail: null,

    category: 'barbell',
  },
  'barbell c-70': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue C-70 Bar',
    link: 'https://www.roguefitness.com/the-rogue-c-70-bar',
    last_avail: null,

    category: 'barbell',
  },
  'rack rml-3fullw': {
    type: 'rmlc',
    senderIDs: {},
    product_name: 'Monster Lite RML-390FULLW Fold Back Wall Mount Power Rack',
    link:
      'https://www.roguefitness.com/monster-lite-rml-390-fullw-fold-back-wall-mount-power-rack',
    last_avail: null,

    category: 'rack',
  },
  'hr-2 conversion': {
    type: 'multi',
    senderIDs: {},
    product_name: 'HR-2 Half Rack Conversion Kit',
    link: 'https://www.roguefitness.com/infinity-hr2-half-rack-conversion-kit',
    last_avail: null,

    category: 'rack',
  },
  'rack rml-390c': {
    type: 'rmlc',
    senderIDs: {},
    product_name: 'Rogue RML-390C Power Rack 3.0',
    link: 'https://www.roguefitness.com/rml-390c-power-rack-3-0',
    last_avail: null,

    category: 'rack',
  },
  'rack rml-690c': {
    type: 'rmlc',
    senderIDs: {},
    product_name: 'Rogue RML-690C Power Rack 3.0',
    link: 'https://www.roguefitness.com/rml-690c-power-rack-3-0',
    last_avail: null,

    category: 'rack',
  },
  skierg: {
    type: 'multi',
    senderIDs: {},
    product_name: 'Concept 2 SkiErg',
    link: 'https://www.roguefitness.com/concept-2-skierg-2',
    last_avail: null,

    category: 'cardio',
  },
  'plate 6-shooter urethane': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue 6-Shooter Urethane Olympic Grip Plates',
    link:
      'https://www.roguefitness.com/rogue-6-shooter-urethane-olympic-grip-plates',
    last_avail: null,

    category: 'plate',
  },
  'm utility seat': {
    type: 'single',
    senderIDs: {},
    product_name: 'Rogue Monster Utility Seat',
    link: 'https://www.roguefitness.com/rogue-monster-utility-seat',
    last_avail: null,

    category: 'm',
  },
  'landmine handles': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue Landmine Handles',
    link: 'https://www.roguefitness.com/rogue-landmine-handles',
    last_avail: null,

    category: 'acc',
  },
  'loading pin': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue Loading Pin',
    link: 'https://www.roguefitness.com/rogue-loading-pin',
    last_avail: null,

    category: 'acc',
  },
  'p-4 pullup': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue P-4 Pull-up System',
    link: 'https://www.roguefitness.com/p4-pullup-system',
    last_avail: null,

    category: 'acc',
  },
  'barbell ssb': {
    type: 'single',
    senderIDs: {},
    product_name: 'SB-1 - Rogue Safety Squat Bar',
    link: 'https://www.roguefitness.com/sb-1-rogue-safety-squat-bar',
    last_avail: null,

    category: 'barbell',
  },
  'm socket': {
    type: 'custom2',
    senderIDs: {},
    product_name: 'Rogue Monster Socket Pull-up Bar',
    link: 'https://www.roguefitness.com/rogue-monster-socket-pull-up-bar',
    last_avail: null,

    category: 'm',
  },
  'ml socket': {
    type: 'custom2',
    senderIDs: {},
    product_name: 'Rogue Monster Lite Socket Pull-up Bar',
    link: 'https://www.roguefitness.com/rogue-monster-lite-socket-pull-up-bar',
    last_avail: null,

    category: 'ml',
  },
  'm socket curl': {
    type: 'custom2',
    senderIDs: {},
    product_name: 'Rogue Monster Socket Pull-up Curl Bar',
    link: 'https://www.roguefitness.com/monster-socket-pull-up-bar-curl-bar',
    last_avail: null,

    category: 'm',
  },
  'ml socket curl': {
    type: 'custom2',
    senderIDs: {},
    product_name: 'Rogue Monster Lite Socket Pull-up Curl Bar',
    link: 'https://www.roguefitness.com/ml-socket-pull-up-bar-curl-bar',
    last_avail: null,

    category: 'ml',
  },
  'm band pegs': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Monster Band Peg 2.0 - 4 Pack',
    link: 'https://www.roguefitness.com/monster-band-pegs-2-0-4-pack',
    last_avail: null,

    category: 'm',
  },
  'speed bag': {
    type: 'custom2',
    senderIDs: {},
    product_name: 'Rogue Rig Mount Speed Bag Platforms',
    link: 'https://www.roguefitness.com/rogue-rig-mount-speed-bag-platforms',
    last_avail: null,

    category: 'acc',
  },
  'ml wall mount kit': {
    type: 'single',
    senderIDs: {},
    product_name: 'Monster Lite Rack Wall Mount Kit',
    link: 'https://www.roguefitness.com/monster-lite-rack-wall-mount-kit',
    last_avail: null,

    category: 'ml',
  },
  'dumbbells urethane': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue Urethane Dumbbells',
    link: 'https://www.roguefitness.com/rogue-urethane-dumbbells-new',
    last_avail: null,

    category: 'cond',
  },
  'squat stand storage pair': {
    type: 'single',
    senderIDs: {},
    product_name: 'Rogue Squat Stand Base Storage - Pair',
    link: 'https://www.roguefitness.com/rogue-squat-stand-base-storage-pair',
    last_avail: null,

    category: 'acc',
  },
  'horizontal plate rack': {
    type: 'single',
    senderIDs: {},
    product_name: 'Rogue Horizontal Plate Rack 2.0',
    link: 'https://www.roguefitness.com/horizontal-plate-rack-2-0',
    last_avail: null,

    category: 'acc',
  },
  'plate hi-temp comp': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue Hi-Temp Competition Training Plates',
    link:
      'https://www.roguefitness.com/rogue-hi-temp-competition-training-plates',
    last_avail: null,

    category: 'plate',
  },
  'plate fractional lb': {
    type: 'multi',
    senderIDs: {},
    product_name: 'Rogue LB Fractional Plates',
    link: 'https://www.roguefitness.com/rogue-lb-fractional-plates',
    last_avail: null,

    category: 'plate',
  },
  'conversion s1 s2': {
    type: 'multi',
    senderIDs: {},
    product_name: 'S-1 to S-2 Conversion Kit',
    link: 'https://www.roguefitness.com/s-1-to-s-2-conversion-kit',
    last_avail: null,
    status: 'new',
    category: 'rack',
  },
  'barbell castro': {
    type: 'single',
    senderIDs: {},
    product_name: 'The Castro Bar',
    link: 'https://www.roguefitness.com/the-castro-bar',
    last_avail: null,
    status: 'new',
    category: 'barbell',
  },
  'm knurled knob': {
    type: 'custom2',
    senderIDs: {},
    product_name: 'Monster Knurled Knob',
    link: 'https://www.roguefitness.com/monster-knurled-knob',
    last_avail: null,
    status: 'new',
    category: 'm',
  },
  'plate york': {
    type: 'multi',
    senderIDs: {},
    product_name: 'York Legacy Iron Plates',
    link: 'https://www.roguefitness.com/york-legacy-iron-plates',
    last_avail: null,
    status: 'new',
    category: 'plate',
  },
  'plate tree york': {
    type: 'single',
    senderIDs: {},
    product_name: 'York Olympic A-Frame Plate Tree',
    link: 'https://www.roguefitness.com/york-olympic-a-frame-plate-tree',
    last_avail: null,
    status: 'new',
    category: 'acc',
  },
  'uk echo color': {
    type: 'multi',
    senderIDs: {},
    product_name: 'UK Rogue Color Echo Bumper Plates',
    link: 'https://www.rogueeurope.eu/rogue-color-echo-bumper-plate-eu',
    last_avail: null,
    category: 'uk',
  },
  'uk echo': {
    type: 'multi',
    senderIDs: {},
    product_name: 'UK Rogue Echo Bumper Plates V2',
    link:
      'https://www.rogueeurope.eu/rogue-echo-bumper-plates-with-white-text-eu',
    last_avail: null,
    category: 'uk',
  },
  'uk p-4 pullup': {
    type: 'single',
    senderIDs: {},
    product_name: 'Rogue P-4 Pull-up System',
    link: 'https://www.rogueeurope.eu/rogue-p-4-pull-up-system',
    last_avail: null,

    category: 'uk',
  },
  'uk rr plate': {
    type: 'multi',
    senderIDs: {},
    product_name: 'UK Rogue RR Plates',
    link: 'https://www.rogueeurope.eu/rogue-rr-bumper-plates-eu',
    last_avail: null,
    category: 'uk',
  },
  'uk bella zinc': {
    type: 'single',
    senderIDs: {},
    product_name: 'UK The Bella Bar 2.0 - Black Zinc',
    link: 'https://www.rogueeurope.eu/rogue-bella-bar-eu',
    last_avail: null,
    category: 'uk',
  },
  'uk opb ss': {
    type: 'single',
    senderIDs: {},
    product_name: 'UK Rogue 20KG Ohio Power Bar - Stainless Steel',
    link:
      'https://www.rogueeurope.eu/rogue-20-kg-ohio-power-bar-stainless-steel-eu',
    last_avail: null,
    category: 'uk',
  },
  'uk opb zinc': {
    type: 'single',
    senderIDs: {},
    product_name: 'UK Rogue 20KG Ohio Power Bar - Black Zinc',
    link: 'https://www.rogueeurope.eu/rogue-20-kg-ohio-power-bar-black-zinc-eu',
    last_avail: null,

    category: 'uk',
  },
  'uk kettlebells': {
    type: 'multi',
    senderIDs: {},
    product_name: 'UK Rogue Kettlebells',
    link: 'https://www.rogueeurope.eu/rogue-kettlebells-eu',
    last_avail: null,

    category: 'uk',
  },
  'uk dumbbells': {
    type: 'multi',
    senderIDs: {},
    product_name: 'UK Rogue KG Dumbbells',
    link: 'https://www.rogueeurope.eu/rogue-kg-dumbbells',
    last_avail: null,

    category: 'uk',
  },
  'uk home timer': {
    type: 'multi',
    senderIDs: {},
    product_name: 'UK Rogue Home Timer',
    link: 'https://www.rogueeurope.eu/rogue-home-timer-eu',
    last_avail: null,

    category: 'uk',
  },
  'uk plate tree': {
    type: 'multi',
    senderIDs: {},
    product_name: 'UK Rogue Vertical Plate Tree 2.0',
    link: 'https://www.rogueeurope.eu/rogue-vertical-plate-tree-2-0-eu',
    last_avail: null,

    category: 'uk',
  },
  'uk bench ab2': {
    type: 'multi',
    senderIDs: {},
    product_name: 'UK AB-2 Adjustable Bench',
    link: 'https://www.rogueeurope.eu/ab-2-adjustable-bench-eu',
    last_avail: null,

    category: 'uk',
  },
  'au bench ab2': {
    type: 'multi',
    senderIDs: {},
    product_name: 'AU AB-2 Adjustable Bench',
    link: 'https://www.rogueaustralia.com.au/ab-2-adjustable-bench-au',
    last_avail: null,
    category: 'au',
  },
  'au barbell opb zinc': {
    type: 'single',
    senderIDs: {},
    product_name: 'AU Rogue 20KG Ohio Power Bar - Black Zinc',
    link:
      'https://www.rogueaustralia.com.au/rogue-20-kg-ohio-power-bar-black-zinc-au',
    last_avail: null,
    category: 'au',
  },
  'au barbell opb ss': {
    type: 'single',
    senderIDs: {},
    product_name: 'AU Rogue 20KG Ohio Power Bar - Stainless Steel',
    link:
      'https://www.rogueaustralia.com.au/rogue-20-kg-ohio-power-bar-stainless-steel-au',
    last_avail: null,
    category: 'au',
  },
  'au sml-1': {
    type: 'multi',
    senderIDs: {},
    product_name: 'AU SML-1 Rogue 70" Monster Lite Squat Stand',
    link:
      'https://www.rogueaustralia.com.au/sml-1-rogue-70-monster-lite-squat-stand-au',
    last_avail: null,
    category: 'au',
  },
  'au ml safety spotter arms': {
    type: 'multi',
    senderIDs: {},
    product_name: 'AU SAML-24 Monster Lite Safety Spotter Arms (Pair)',
    link:
      'https://www.rogueaustralia.com.au/saml-24-monster-lite-spotter-arms-pair-au',
    last_avail: null,
    category: 'au',
  },
  'au plate cal': {
    type: 'multi',
    senderIDs: {},
    product_name: 'AU Rogue Calibrated KG Steel Plates',
    link:
      'https://www.rogueaustralia.com.au/rogue-calibrated-kg-steel-plates-au',
    last_avail: null,
    category: 'au',
  },
  'au rml-390f': {
    type: 'multi',
    senderIDs: {},
    product_name: 'AU RML-390F Flat Foot Monster Lite Rack',
    link:
      'https://www.rogueaustralia.com.au/rml-390f-flat-foot-monster-lite-rack-au',
    last_avail: null,

    category: 'au',
  },
  'au model d rower': {
    type: 'single',
    senderIDs: {},
    product_name: 'AU Black Concept 2 Model D Rower - PM5',
    link:
      'https://www.rogueaustralia.com.au/black-concept-2-model-d-rower-pm5-au',
    last_avail: null,

    category: 'au',
  },
  'barbell squat': {
    type: 'single',
    senderIDs: {},
    product_name: 'Rogue 32MM Squat Bar',
    link: 'https://www.roguefitness.com/rogue-32-mm-squat-bar',
    last_avail: null,
    category: 'barbell',
  },
};
module.exports = searchUrls;
