USE rogue;

INSERT INTO items(short_name, full_name, link, link_type) 
VALUES
('plate hi-temp',  'Rogue Bumper Plates by Hi-Temp', 'https://www.roguefitness.com/rogue-hi-temp-bumper-plates', 'multi'),
('plate hg2', 'Rogue HG 2.0 Bumper Plates', 'https://www.roguefitness.com/rogue-hg-2-0-bumper-plates', 'multi'),
('plate comp lb',  'Rogue LB Competition Plates', 'https://www.roguefitness.com/rogue-competition-plates', 'multi'),
('plate black lb', 'Rogue Black Training LB Plates', 'https://www.roguefitness.com/rogue-black-training-lb-color-stripe-plates', 'multi'),
('plate black lb2', 'Rogue LB Training 2.0 Plates', 'https://www.roguefitness.com/rogue-lb-training-2-0-plates', 'multi'),
('plate black kg', 'Rogue Black Training KG Plates', 'https://www.roguefitness.com/rogue-black-training-kg-striped-plates', 'multi'),
('plate echo', 'Rogue Echo Bumper Plates', 'https://www.roguefitness.com/rogue-echo-bumper-plates-with-white-text', 'multi'),
('plate echo color', 'Rogue Color Echo Bumper Plates', 'https://www.roguefitness.com/rogue-color-echo-bumper-plate', 'multi'),
('plate machined', 'Rogue Machined Olympic Plates', 'https://www.roguefitness.com/rogue-machined-olympic-plates', 'multi'),
('plate fleck', 'Rogue Fleck Plate', 'https://www.roguefitness.com/rogue-fleck-plates', 'multi'),
('plate olympic', 'Rogue Olympic Plates', 'https://www.roguefitness.com/rogue-olympic-plates', 'multi'),
('plate cal', 'Rogue Calibrated LB Steel Plates', 'https://www.roguefitness.com/rogue-calibrated-lb-steel-plates', 'multi'),
('plate change', 'Rogue LB Change Plates', 'https://www.roguefitness.com/rogue-lb-change-plates', 'multi'),
('plate 6-shooter', 'Rogue 6-Shooter Olympic Grip Plates', 'https://www.roguefitness.com/rogue-6-shooter-olympic-plates', 'multi'),
('plate cal kg', 'Rogue Calibrated KG Steel Plates', 'https://www.roguefitness.com/rogue-calibrated-kg-steel-plates', 'multi'),
('plate tree', 'Rogue Vertical Plate Tree 2.0', 'https://www.roguefitness.com/rogue-vertical-plate-tree-2-0', 'multi'),
('barbell op oxide', 'The Ohio Bar - Black Oxide', 'https://www.roguefitness.com/rogue-ohio-bar-black-oxide', 'single'),
('barbell op zinc', 'The Ohio Bar - Black Zinc', 'https://www.roguefitness.com/the-ohio-bar-black-zinc', 'single'),
('barbell op ecoat', 'The Ohio Bar - E-Coat', 'https://www.roguefitness.com/the-ohio-bar-2-0-e-coat', 'single'),
('barbell op ss', 'The Ohio Bar - Stainless Steel', 'https://www.roguefitness.com/stainless-steel-ohio-bar', 'single'),
('barbell op cerakote', 'The Ohio Bar - Cerakote', 'https://www.roguefitness.com/the-ohio-bar-cerakote', 'single'),
('barbell opb steel', 'Rogue 45LB Ohio Power Bar - Bare Steel', 'https://www.roguefitness.com/rogue-45lb-ohio-power-bar-bare-steel', 'single'),
('barbell opb ecoat', 'Rogue 45LB Ohio Power Bar - E-Coat', 'https://www.roguefitness.com/rogue-ohio-power-bar-e-coat', 'single'),
('barbell opb zinc', 'Rogue 45LB Ohio Power Bar - Black Zinc', 'https://www.roguefitness.com/rogue-45lb-ohio-power-bar-black-zinc', 'single'),
('barbell opb ss', 'Rogue 45LB Ohio Power Bar - Stainless Steel', 'https://www.roguefitness.com/rogue-45lb-ohio-power-bar-stainless', 'single'),
('barbell opb ss kg', 'Rogue 20KG Ohio Power Bar - Stainless Steel', 'https://www.roguefitness.com/rogue-20-kg-ohio-power-bar-stainless-steel', 'single'),
('barbell opb cerakote', 'Rogue 45LB Ohio Power Bar - Cerakote', 'https://www.roguefitness.com/rogue-45lb-ohio-powerlift-bar-cerakote', 'single'),
('bone 29', 'Boneyard 29mm Bars', 'https://www.roguefitness.com/rogue-29mm-boneyard-bars', 'bone'),
('bone 28.5', 'Boneyard 28.5mm Bars', 'https://www.roguefitness.com/rogue-28-5-mm-boneyard-bars', 'bone'),
('bone dead', 'Boneyard Deadlift Bars', 'https://www.roguefitness.com/rogue-boneyard-ohio-deadlift-bar', 'bone'),
('bone used', 'Used Barbells', 'https://www.roguefitness.com/miscellaneous-barbells-used', 'bone'),
('bone oso pro', 'Boneyard OSO Pro Collars', 'https://www.roguefitness.com/boneyard-oso-pro-collars-closeout', 'bone'),
('bella ecoat', 'The Bella Bar 2.0 - E-Coat', 'https://www.roguefitness.com/the-bella-bar-2-0-e-coat', 'single'),
('bella zinc', 'The Bella Bar 2.0 - Black Zinc', 'https://www.roguefitness.com/rogue-bella-bar-2-0-black-zinc', 'single'),
('bella ss', 'The Bella Bar 2.0 - Stainless Steel', 'https://www.roguefitness.com/the-bella-bar-2-0-stainless', 'single'),
('curl cerakote', 'Rogue Curl Bar - Cerakote', 'https://www.roguefitness.com/rogue-curl-bar-cerakote', 'single'),
('curl', 'Rogue Curl Bar', 'https://www.roguefitness.com/rogue-curl-bar', 'multi'),
('curl rackable', 'Rogue Rackable Curl Bar', 'https://www.roguefitness.com/rogue-rackable-curl-bar', 'single'),
('barbell rogue 2.0', 'The Rogue Bar 2.0', 'https://www.roguefitness.com/the-rogue-bar-2-0', 'single'),
('barbell echo 2.0', 'Rogue Echo Bar 2.0', 'https://www.roguefitness.com/rogue-echo-bar', 'single'),
('barbell freedom', 'Rogue Freedom Bar - 28.5MM', 'https://www.roguefitness.com/cerakote-28-5-mm-freedom-bar', 'single'),
('bike echo', 'Rogue Echo Bike', 'https://www.roguefitness.com/rogue-echo-bike', 'multi'),
('bench flat 2.0', 'Rogue Flat Utility Bench 2.0', 'https://www.roguefitness.com/rogue-flat-utility-bench', 'single'),
('bench adj 2.0', 'Rogue Adjustable Bench 2.0', 'https://www.roguefitness.com/rogue-adjustable-bench-2-0', 'multi'),
('bench ab2', 'AB-2 Adjustable Bench', 'https://www.roguefitness.com/ab-2-adjustable-bench', 'multi'),
('bench ab3', 'Rogue AB-3 Adjustable Bench', 'https://www.roguefitness.com/rogue-ab-3-adjustable-bench', 'multi'),
('bench thompson', 'Thompson Fat Pad', 'https://www.roguefitness.com/thompson-fatpad', 'single'),
('bench fatpad', 'Rogue Competition Fat Pad', 'https://www.roguefitness.com/rogue-competition-fat-pad', 'single'),
('bench foldup', 'Rogue Fold Up Utility Bench', 'https://www.roguefitness.com/rogue-fold-up-utility-bench', 'single'),
('bench westside 2.0', 'Rogue Westside Bench 2.0', 'https://www.roguefitness.com/rogue-westside-bench-2-0', 'multi'),
('bench monster westside', 'Rogue Monster Westside Bench', 'https://www.roguefitness.com/rogue-monster-westside-bench', 'multi'),
('squat sml-2', 'SML-2 Rogue 90" Monster Lite Squat Stand', 'https://www.roguefitness.com/sml-2-rogue-90-monster-lite-squat-stand', 'multi'),
('squat sml-3', 'SML-3 Rogue 108" Monster Lite Squat Stand', 'https://www.roguefitness.com/sml-3-rogue-108-monster-lite-squat-stand', 'multi'),
('squat s-2', 'Rogue S-2 Squat Stand 2.0', 'https://www.roguefitness.com/rogue-s2-squat-stand-2-0', 'multi'),
('squat echo', 'Rogue Echo Squat Stand 2.0', 'https://www.roguefitness.com/rogue-echo-squat-stand-2-0', 'single'),
('yoke y1', 'Y-1 Rogue Yoke', 'https://www.roguefitness.com/rogue-yoke', 'multi'),
('yoke y2', 'Y-2 Rogue Yoke', 'https://www.roguefitness.com/y2-yoke', 'multi'),
('rack rml-390f', 'RML-390F Flat Foot Monster Lite Rack', 'https://www.roguefitness.com/rml-390f-flat-foot-monster-lite-rack', 'multi'),
('rack rml-490', 'Rogue RML-490 Power Rack', 'https://www.roguefitness.com/rogue-rml-490-power-rack', 'multi'),
('rack rml-690', 'Rogue RML-690 Power Rack', 'https://www.roguefitness.com/rml-690-power-rack', 'multi'),
('rack r-3', 'Rogue R-3 Power Rack', 'https://www.roguefitness.com/rogue-r-3-power-rack', 'multi'),
('rower pm5', 'Black Concept 2 Model D Rower - PM5', 'https://www.roguefitness.com/black-concept-2-model-d-rower-pm5', 'single'),
('abram ghd', 'Rogue Abram GHD 2.0', 'https://www.roguefitness.com/rogue-abram-glute-ham-developer-2-0', 'single'),
('monster ghd', 'Rogue Monster Swing Arm GHD', 'https://www.roguefitness.com/rogue-monster-swing-arm-ghd', 'multi'),
('echo ghd', 'Rogue 3x3 Echo GHD', 'https://www.roguefitness.com/rogue-echo-ghd', 'multi'),
('mini dl jack', 'Mini Deadlift Bar Jack', 'https://www.roguefitness.com/mini-deadlift-bar-jack', 'single'),
('kettlebells', 'Rogue Kettlebells', 'https://www.roguefitness.com/rogue-kettlebells', 'multi'),
('dumbbells', 'Rogue Dumbbells', 'https://www.roguefitness.com/rogue-dumbbells', 'multi');